name: retail_lakehouse
version: 1.0.0
config-version: 2
profile: retail_lakehouse
model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
clean-targets: ["target", "dbt_packages"]
models:
  retail_lakehouse:
    +file_format: delta
    silver: {+materialized: table, +schema: silver}
    intermediate: {+materialized: view, +schema: intermediate}
    gold: {+materialized: table, +schema: gold}
snapshots:
  retail_lakehouse:
    +target_schema: snapshots
    +file_format: delta
